---
- name: Permissions for elasticsearch
  become: yes
  file:
    state: directory
    mode: 0777
    path: /var/log/elasticsearch

- name: Permissions for elasticsearch volume
  become: yes
  file:
    state: directory
    path: /srv/newsblur/docker/volumes
    recurse: yes
    owner: nb
    group: nb

- name: System max_map_count increase
  become: yes
  ansible.posix.sysctl:
    name: vm.max_map_count
    value: "262144"
    state: present
    
- name: Start Elasticsearch Docker container
  docker_container:
    name: elasticsearch
    image: elasticsearch:7.14.0
    state: started
    hostname: "{{ inventory_hostname }}"
    ports:
      - '9200:9200'
      - '9300:9300'
    restart_policy: unless-stopped
    container_default_behavior: no_defaults
    networks_cli_compatible: yes
    # network_mode: host
    network_mode: default
    networks:
      - name: newsblurnet
        aliases: 
          - elasticsearch
    volumes:
      - /srv/newsblur/docker/volumes/elasticsearch:/usr/share/elasticsearch/data
      - /var/log/elasticsearch/:/var/log/elasticsearch/
      - /srv/newsblur/config/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

- name: Register elasticsearch in consul
  tags: consul
  become: yes
  template:
    src: consul_service.json
    dest: /etc/consul.d/elasticsearch.json
  notify:
    - reload consul

- name: Add sanity checkers cronjob for disk usage
  become: yes
  cron:
    name: disk_usage_sanity_checker
    user: root
    cron_file: /etc/cron.hourly/disk_usage_sanity_checker
    job: >-
      docker pull newsblur/newsblur_python3:latest;
      docker run --rm -it
      OUTPUT=$(eval sudo df / | head -n 2 |  tail -1);
      -v /srv/newsblur:/srv/newsblur
      --network=newsblurnet
      --hostname {{ ansible_hostname }} 
      newsblur/newsblur_python3 /srv/newsblur/utils/monitor_disk_usage.py $OUTPUT
  tags:
    - sanity-checker
