---
- name: Ensure certificates directory exists
  file:
    path: /srv/newsblur/config/certificates
    state: directory

- name: Copy APNS certificates
  copy:
    src: "/srv/secrets-newsblur/certificates/ios/{{ item }}"
    dest: "/srv/newsblur/config/certificates/{{ item }}"
    mode: 0400
  with_items:
    - aps.p12.pem
