route:
  group_by: [alertname]
  receiver: email-me
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 5m

receivers:
- name: email-me
  email_configs:
  - to: ${ALERT_RECEIVER_EMAIL}
    from: ${FROM_EMAIL}
    smarthost: ${SMARTHOST}
    auth_username: ${AUTH_USERNAME}
    auth_identity: ${AUTH_IDENTITY}
    auth_password: ${AUTH_PASSWORD}
