---
# File: main.yml - Handlers for Consul

- name: reload consul
  become: yes
  service:
    name: consul
    state: reloaded
  listen: reload consul

- name: reload haproxy
  become: yes
  command: docker kill --signal HUP haproxy
  listen: reload haproxy

- name: restart haproxy
  become: yes
  command: docker restart haproxy
  listen: restart haproxy
