---
# File: main.yml - Handlers for Consul

- name: reload consul configuration
  become: yes
  service:
    name: consul
    state: reloaded
  listen: reload consul

- name: restart redis
  become: yes
  command: docker restart redis
  listen: restart redis
